### ISSUE TITLE
ADT liquid chunks are not loading vertex data

### ISSUE THREAD

**Issue by Nihlus** [Nihlus/libwarcraft#9]
Due to ADT tiles not loading with DBC values, the vertex format can't be inferred. Might be possible to compute the relevant vertex format from the size of the data block.

Implemented:
- [x] GameWorld wrapper class that holds and loads terrain

Changes required:
- [ ] Add passing in of DBC liquid type to TerrainTile (TerrainTile.cs#175)
- [ ] Add loading of specific vertex format based on flags (TerrainLiquid.cs#212)
- [ ] Add loading of terrain tiles from wrapper GameWorld class (GameWorld.cs#80)
